POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username":"user",
  "email":"user@gmail.com",
  "password":"12345",
  "confPassword":"12345",
  "role":"user"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345"
}

###
GET http://localhost:5000/v1/users


### POSTS
GET http://localhost:5000/v1/posts

###
POST http://localhost:5000/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDM1OTJmOTU4ODlmNjQ0YjhjMDZiNSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mjg4NzU3ODEsImV4cCI6MTcyODg3NzU4MX0.Ow0Haa2bzZyBcghZIOPS8yYgAKMF7gQSQIT2chBE040

{
    "body": "Post by Admin 1"
}

###
DELETE http://localhost:5000/v1/posts/670c8e338f330b59346e8784
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDM1OTJmOTU4ODlmNjQ0YjhjMDZiNSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mjg4NzU3ODEsImV4cCI6MTcyODg3NzU4MX0.Ow0Haa2bzZyBcghZIOPS8yYgAKMF7gQSQIT2chBE040


### COMMENTS
GET http://localhost:5000/v1/comments

###
GET http://localhost:5000/v1/comments/67078a152d8a50aac7268487

###
POST http://localhost:5000/v1/comments/670c92abb9a3ce7dfcdbf0e8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDNjYzY0Yjc5NTNjY2FjZmJhMGQwNyIsInVzZXJuYW1lIjoidXNlciIsInJvbGUiOiJ1c2VycyIsImlhdCI6MTcyODg3NTU3OSwiZXhwIjoxNzI4ODc3Mzc5fQ.pt7hDXmz96Cw_sS53CoQs2gcMf6Z9t0SAmZckO_9s-c

{
  "body":"comments By user 1" 
}

###
DELETE http://localhost:5000/v1/comments/6708c6a0bd56f26a5db6cfca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDM1OTJmOTU4ODlmNjQ0YjhjMDZiNSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mjg2MjgzNzQsImV4cCI6MTcyODYzMDE3NH0.5frHIMg5zSYsvfO86k2fu9TkZhEZmjQdI3_R820qqLY

###
PATCH http://localhost:5000/v1/comments/6708c6bebd56f26a5db6cfcd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDM1OTJmOTU4ODlmNjQ0YjhjMDZiNSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mjg2MjczMTcsImV4cCI6MTcyODYyOTExN30.IhRGhZzeqbu46MpXECSIuTnAXq65IiuWWIfYOHU9DGc

{
  "body":"comments by admin 1 updateeeee"
}
